### ISSUE TITLE
Recipe for Node, Docker, Nodemon and Babel

### ISSUE THREAD

**Issue by sbernaldev** [Microsoft/vscode-recipes#126]
Hi, I'm trying to modify Docker's with Node and typescript in order to adapt into Javascript with Babel.

My package.json scripts
```
  "scripts": {
    "debug": "nodemon --watch dist/ --inspect=0.0.0.0 --nolazy -L dist/index.js",
    "docker-debug": "docker-compose up",
    "start": "node dist/index.js",
    "postinstall": "babel src/ --out-dir dist/ --source-maps",
    "watch": "babel src/ --watch --out-dir dist/ --source-maps",
  },
```
My launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "launch",
        "name": "Launch in Docker",
        "preLaunchTask": "watch",
        "runtimeExecutable": "npm",
        "runtimeArgs": [ "run", "docker-debug" ],
        "port": 9229,
        "restart": true,
        "timeout": 60000,
        "localRoot": "${workspaceFolder}",
        "remoteRoot": "/app",
        "outFiles": [
          "${workspaceFolder}/dist/**/*.js"
        ],
        "console": "integratedTerminal",
        "internalConsoleOptions": "neverOpen"
      }
    ]
  }
```

My tasks.json
```
{
  "version": "0.1.0",
  "tasks": [{
    "taskName": "watch",
    "command": "npm",
    "args": ["run", "watch"],
    "isShellCommand": true,
    "isBackground": true,
    "isBuildCommand": true,
    "problemMatcher": [],
    "showOutput": "always"
  }]
}
```
My dockerfile
```
FROM node:8.11

RUN apt-get update && apt-get install -y \
  rubygems \
  ruby2.1-dev

RUN gem install -N mailcatcher

WORKDIR /app

COPY . /app
RUN npm install

EXPOSE 3001 1080 9229
CMD [ "npm", "start" ]

```

My docker-compose.json
```
version: "2"
services:
  api:
    build: .
    ports:
      - "3001:3001"
      - "1080:1080"
      - "9229:9229"
    command: npm run debug
    volumes:
      - ./dist:/app/dist
    depends_on:
      - mongo
    env_file: .env

  mongo:
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"
    command: --smallfiles --logpath=/dev/null # --quiet

```

But when I try to run the debugger, it begins to create a lot of terminals in loop
https://prnt.sc/knmfb2

If I set "restart": true to false, then it doesn't loop but debugger doesn't get attached.

Any tips? Thanks
