### ISSUE TITLE
Debugger breakpoint takes a while to stop

### ISSUE THREAD

**Issue by cavalos0086** [Microsoft/vscode-recipes#193]
# Issue:

When I use the launch docker debugger method, the debugger starts but the breakpoints don't work. I have to wait about a min for the breakpoints to work. 

# Information:
Vscode version: `1.31.1 (1.31.1)`
Docker desktop community version `2.0.0.3(31259)

### Launch configuration:
```
{
      "type": "node",
      "request": "launch",
      "name": "Launch in Docker",
      "preLaunchTask": "tsc-watch",
      "protocol": "auto",
      "runtimeExecutable": "npm",
      "runtimeArgs": [ "run", "docker-debug" ],
      "port": 5858,
      "restart": true,
      "timeout": 60000,
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/server",
      "outFiles": [
        "${workspaceFolder}/dist/**/*.js"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    },
```

### tasks configuration:
```
"tasks": [
    {
      "label": "tsc-watch",
      "isBackground": true,
      "type": "typescript",
      "tsconfig": "src/tsconfig.json",
      "option": "watch",
    }
  ]
```

**Comment by auchenberg** [comment]
How does your `npm run docker-debug` script look?

**Comment by cavalos0086** [comment]
`"docker-debug": "docker-compose up",`
and the docker-compose file:
```
version: "2"

services:
  web:
    build: .
    command: npm run debug
    volumes:
      - ./dist:/server/dist
    ports:
      - "3000:3000"
      - "5858:5858"
```
