### ISSUE TITLE
Rails in Docker debugging recipe doesn't work

### ISSUE THREAD

**Issue by vcc-LG** [microsoft/vscode-recipes#221]
I have replicated the steps in the 'Bonus' section of the 'Ruby on Rails debugging in VS Code' page, and am unable to launch the Rails server and attach a VS Code debugger.

My `docker-compose.yml` looks like:

```
version: '3'
services:
  web:
    build: .
    command: bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162  -- rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/myapp
    ports:
     - "1234:1234"
     - "3000:3000"
     - "26162:26162"
```

and my `Dockerfile` looks like:

```
FROM ruby:2.5
RUN apt-get update -qq
RUN mkdir /myapp
WORKDIR /myapp
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
COPY . /myapp

EXPOSE 3000
EXPOSE 1234
EXPOSE 26162

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]
```

My `launch.json` file looks like:

```
        {
            "name": "Attach to Docker",
            "type": "Ruby",
            "request": "attach",
            "remotePort": "1234",
            "remoteHost": "0.0.0.0",
            "remoteWorkspaceRoot": "/myapp",
            "cwd": "${workspaceRoot}",
            "showDebuggerOutput": true
        },
```

When I build and run `docker-compose up`, I see this in my Docker logs:

```
Fast Debugger (ruby-debug-ide 0.6.1, debase 0.2.2, file filtering is supported) listens on 0.0.0.0:1234
```

but browsing to `localhost:3000` gives an `ERR_EMPTY_RESPONSE` error in Chrome and no pages load. When I hit the 'play' button in the Debug section of VSCode I see the debugger toolbar (pause, step-over etc.) but no pages load in the browser.

Would it be possible for someone at VSCode to investigate and update the details on this recipe to ensure they work properly for a vanilla Rails app and VSCode install?
