### ISSUE TITLE
If docker-compose.yml has more than 1 services is it possible to attach node debugger to the node service?

### ISSUE THREAD

**Issue by qiulang** [Microsoft/vscode-recipes#29]
Hi, I found all the examples I can find all have one problem, the docker-compose.yml only has one service. In a real scenario, which docker-compose.yml has more than one services I don't know how to attach debugger the node service. I don't know how to set remoteRoot?  Or is it possible to attach node debugger to the node service?

**Comment by tarunlalwani** [comment]
If you have a node service and other supporting services like DB, redis etc, then it really doesn't matter. You are just concerned about the Node service and its port mapping and its volume mapping. remoteRoot will be the folder where the code is residing inside the container

**Comment by qiulang** [comment]
I did have one node service and other supporting services. But I just can't attach the debugger to the node service. Can you show me how to do that?
My docker-compose.debug.yml looks like this
```
version: '3'
services:
  nginx:
    ...
  node:
    build: ./node
    links:
      - mongo:mongo
      - redis:redis
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./node:/app
    command: node --inspect bin/www
  mongo:
     ...
  redis:
    ...
```
This is my folder looks like:
├── .vscode
│   ├── launch.json
├── docker-compose.debug.yml
├── docker-compose.yml
├── nginx
│   ├── Dockerfile
│   ├── README.md
│   └── nginx.conf
├── node
│   ├── Dockerfile
│   ├── README.md
│   ├── app
│   ├── app.js
│   ├── bin
│   ├── node_modules
│   ├── package.json
│   ├── public
│   ├── views

launch.json is this:
```

        "configurations": [
            {
                "name": "Docker: Attach to Node",
                "type": "node",
                "request": "attach",
                "port": 9229,
                "address": "localhost",
                "localRoot": "${workspaceRoot}",
                "remoteRoot": "app"
            }
        ]
```

When docker-compose -f docker-compose.debug.yml up I saw this
Debugger listening on ws://127.0.0.1:9229/ce75a092-f013-4981-86b6-a86ff3900514

But the debugger said "cannot connect to runtime process"
